# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('description_ru', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('description_en', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('file', models.FileField(upload_to='publications/%Y/%m/%d/', verbose_name='Файл')),
                ('cover', models.ImageField(upload_to='publications_cover/%Y/%m/%d/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
