# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20160725_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationimage',
            name='publication',
        ),
    ]
