# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publicationimage_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-date',), 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='publicationimage',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Изображение публикации', 'verbose_name_plural': 'Изображения публикации'},
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Дата'),
        ),
    ]
