# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20160725_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, help_text='Сортировка по этому полю', verbose_name='Дата'),
        ),
    ]
