# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20160725_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationimage',
            name='publication',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications.Publication', verbose_name='Публикация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
