# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_ru', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_ru', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_en', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_en', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('annotation_ru', models.CharField(blank=True, max_length=1024, verbose_name='Аннотация')),
                ('content_ru', models.TextField(blank=True, verbose_name='Текст')),
                ('annotation_en', models.CharField(blank=True, max_length=1024, verbose_name='Аннотация')),
                ('content_en', models.TextField(blank=True, verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним')),
                ('cover', models.ImageField(upload_to='projects_cover/%Y/%m/%d/', verbose_name='Обложка')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='projects_thumb/%Y/%m/%d/', verbose_name='Превью')),
            ],
            options={
                'verbose_name_plural': 'Проекты',
                'verbose_name': 'Проект',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag'),
        ),
    ]
