# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160613_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
    ]
