# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_ru', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_ru', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_en', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_en', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('idea_ru', models.TextField(blank=True, verbose_name='Идея')),
                ('content_ru', models.TextField(blank=True, verbose_name='Текст')),
                ('idea_en', models.TextField(blank=True, verbose_name='Идея')),
                ('content_en', models.TextField(blank=True, verbose_name='Текст')),
                ('date_publication', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Дата публикации')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним')),
                ('cover', models.ImageField(upload_to='projects_cover/%Y/%m/%d/', verbose_name='Обложка')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='projects_thumb/%Y/%m/%d/', verbose_name='Превью')),
                ('square_ru', models.CharField(blank=True, max_length=255, verbose_name='Площадь')),
                ('ceil_ru', models.CharField(blank=True, max_length=255, verbose_name='Высота потолков')),
                ('square_en', models.CharField(blank=True, max_length=255, verbose_name='Площадь')),
                ('ceil_en', models.CharField(blank=True, max_length=255, verbose_name='Высота потолков')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, verbose_name='Спален')),
            ],
            options={
                'verbose_name': 'Интерьер',
                'verbose_name_plural': 'Интерьеры',
            },
        ),
    ]
