# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interior',
            old_name='ceil_en',
            new_name='ceil',
        ),
        migrations.RenameField(
            model_name='interior',
            old_name='square_en',
            new_name='square',
        ),
        migrations.RemoveField(
            model_name='interior',
            name='ceil_ru',
        ),
        migrations.RemoveField(
            model_name='interior',
            name='square_ru',
        ),
    ]
