# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_ru', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_ru', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_en', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_en', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Текст')),
                ('content_en', models.TextField(blank=True, verbose_name='Текст')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним')),
                ('template', models.CharField(choices=[('index', 'Главная')], max_length=50, verbose_name='Шаблон')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'verbose_name': 'Страница',
            },
        ),
    ]
