# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160624_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('index', 'Главная'), ('about', 'О Нас'), ('contacts', 'Контакты'), ('projects', 'Проекты'), ('interiors', 'Интерьеры'), ('blog', 'Блог'), ('search', 'Поиск')], max_length=50, verbose_name='Шаблон'),
        ),
    ]
