# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20160730_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='main_slides/%Y/%m/%d/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('order', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('index', 'Главная'), ('about', 'О Нас'), ('contacts', 'Контакты'), ('projects', 'Проекты'), ('interiors', 'Интерьеры'), ('blog', 'Блог'), ('blog_tags', 'Блог Теги'), ('search', 'Поиск')], max_length=50, verbose_name='Шаблон'),
        ),
    ]
