# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_ru', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_ru', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (title)')),
                ('keywords_en', models.CharField(blank=True, max_length=1024, verbose_name='Ключевые слова')),
                ('description_en', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (h1)')),
                ('authors_ru', models.CharField(blank=True, max_length=1024, verbose_name='Авторы')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('date_constructed_ru', models.CharField(blank=True, max_length=255, verbose_name='Дата постройки')),
                ('date_planning_ru', models.CharField(blank=True, max_length=255, verbose_name='Проектирование')),
                ('date_realization_ru', models.CharField(blank=True, max_length=255, verbose_name='Реализация')),
                ('idea_ru', models.TextField(blank=True, verbose_name='Идея')),
                ('content_ru', models.TextField(blank=True, verbose_name='Текст')),
                ('authors_en', models.CharField(blank=True, max_length=1024, verbose_name='Авторы')),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('date_constructed_en', models.CharField(blank=True, max_length=255, verbose_name='Дата постройки')),
                ('date_planning_en', models.CharField(blank=True, max_length=255, verbose_name='Проектирование')),
                ('date_realization_en', models.CharField(blank=True, max_length=255, verbose_name='Реализация')),
                ('idea_en', models.TextField(blank=True, verbose_name='Идея')),
                ('content_en', models.TextField(blank=True, verbose_name='Текст')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним')),
                ('cover', models.ImageField(upload_to='projects_cover/%Y/%m/%d/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name_plural': 'Проекты',
                'verbose_name': 'Проект',
            },
        ),
    ]
