# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=models.ImageField(default='', upload_to='projects_thumb/%Y/%m/%d/', verbose_name='Превью'),
            preserve_default=False,
        ),
    ]
